# run: conda env create --name kpd --file environment.yml
name: kpd

dependencies:
  - python=3.11
  - numpy=1.24 
  - ipykernel=6.25
  - notebook=6.5
  - matplotlib=3.7
  - pandas=2.0
  - pip=23.2
  - pip:
    - jax[cpu]
    - diffrax
